import { Questrial } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { AuthProvider } from "./authentication/login/Context/auth";

const inter = Questrial({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Job Portal Diya Interactive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
